# Generated by Django 5.1.2 on 2024-10-20 10:18

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyResourcesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resource_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Resources_Category', models.CharField(choices=[('MATERIALS', 'MATERIALS'), ('Labor', 'Labor'), ('EQUIPMENT', 'EQUIPMENT'), ('Subcontractors', 'Subcontractors'), ('OTHERS', 'OTHERS')], default='', max_length=255)),
                ('Resource_Code_L1', models.CharField(blank=True, max_length=255, null=True)),
                ('Resource_Code_L2', models.CharField(blank=True, max_length=255, null=True)),
                ('Resource_Code_L3', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_of_Measure', models.DateField(null=True)),
                ('Budget_Unit_Cost', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Resources Table',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscription', models.CharField(choices=[('Starter', 'Starter'), ('Company', 'Company'), ('Enterprise', 'Enterprise')], default='Starter', max_length=255)),
                ('Company_Id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('Company_Legal_Name', models.CharField(max_length=255)),
                ('Company_Type', models.CharField(choices=[('Owner', 'Owner'), ('Construction Management', 'Construction Management'), ('Main Contractor', 'Main Contractor'), ('Subcontractor', 'Subcontractor')], default='Owner', max_length=255)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Company_Website', models.CharField(blank=True, max_length=255, null=True)),
                ('Tax_Identification_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Primary_Contact_Person', models.CharField(blank=True, max_length=255, null=True)),
                ('Company_Logo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Table',
            },
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('Project_Name', models.CharField(max_length=255)),
                ('Project_Start_Date', models.DateField(null=True)),
                ('Short_Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Default_Workflow', models.CharField(blank=True, max_length=255, null=True)),
                ('Note_book', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
            options={
                'verbose_name_plural': 'Project Table',
            },
        ),
    ]
