# Generated by Django 5.1.2 on 2024-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetailstable',
            name='Company_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='Company_Logo/'),
        ),
    ]
