# Generated by Django 5.1.2 on 2024-10-23 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0002_alter_companydetailstable_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyresourcestable',
            name='Company_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable'),
        ),
    ]
