# Generated by Django 5.1.2 on 2024-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0003_companyresourcestable_company_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyresourcestable',
            name='Budget_Unit_Cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyresourcestable',
            name='Unit_of_Measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
