# Generated by Django 5.1.2 on 2024-10-23 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0004_alter_companyresourcestable_budget_unit_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttable',
            name='Assigned_User',
            field=models.ManyToManyField(default=None, related_name='project_assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
