# Generated by Django 5.1.2 on 2024-10-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0005_projecttable_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyresourcestable',
            name='Resources_Category',
        ),
        migrations.AlterField(
            model_name='companyresourcestable',
            name='Resource_Code_L1',
            field=models.CharField(choices=[('MATERIALS', 'MATERIALS'), ('Labor', 'Labor'), ('EQUIPMENT', 'EQUIPMENT'), ('Subcontractors', 'Subcontractors'), ('OTHERS', 'OTHERS')], default='', max_length=255),
        ),
    ]
