# Generated by Django 5.1.2 on 2024-10-31 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0006_remove_companyresourcestable_resources_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_Code_L1_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resource_Code_L1', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
        ),
        migrations.AlterField(
            model_name='companyresourcestable',
            name='Resource_Code_L1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.resource_code_l1_table'),
        ),
        migrations.CreateModel(
            name='Resource_Code_L2_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resource_Code_L2', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
        ),
        migrations.AlterField(
            model_name='companyresourcestable',
            name='Resource_Code_L2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.resource_code_l2_table'),
        ),
        migrations.CreateModel(
            name='Resource_Code_L3_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resource_Code_L3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
        ),
        migrations.AlterField(
            model_name='companyresourcestable',
            name='Resource_Code_L3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.resource_code_l3_table'),
        ),
    ]
