# Generated by Django 5.1.2 on 2024-10-31 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0007_resource_code_l1_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource_code_l2_table',
            name='Resource_Code_L1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.resource_code_l1_table'),
        ),
        migrations.AddField(
            model_name='resource_code_l3_table',
            name='Resource_Code_L1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.resource_code_l1_table'),
        ),
        migrations.AddField(
            model_name='resource_code_l3_table',
            name='Resource_Code_L2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.resource_code_l2_table'),
        ),
    ]
