# Generated by Django 5.1.2 on 2024-11-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0008_resource_code_l2_table_resource_code_l1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource_code_l1_table',
            options={'verbose_name': 'Resource Code Level 1', 'verbose_name_plural': 'Resource Codes Level 1'},
        ),
        migrations.AlterModelOptions(
            name='resource_code_l2_table',
            options={'verbose_name': 'Resource Code Level 2', 'verbose_name_plural': 'Resource Codes Level 2'},
        ),
        migrations.AlterModelOptions(
            name='resource_code_l3_table',
            options={'verbose_name': 'Resource Code Level 3', 'verbose_name_plural': 'Resource Codes Level 3'},
        ),
    ]
