# Generated by Django 5.1.2 on 2024-10-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation_Assemblies_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assembly_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Assembly_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Resource_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Resource_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_of_Measure', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Assembly_Unit_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Material_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Labor_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Equipment_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Subcontractors_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('OTHERS_Cost', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
