# Generated by Django 5.1.2 on 2024-11-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0001_initial'),
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation_assemblies_table',
            name='Company_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable'),
        ),
        migrations.CreateModel(
            name='Assemblies_Code_L1_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assemblies_Code_L1', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
            options={
                'verbose_name': 'Assemblies Code Level 1',
                'verbose_name_plural': 'Assemblies Codes Level 1',
            },
        ),
        migrations.AddField(
            model_name='estimation_assemblies_table',
            name='Assemblies_Code_L1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.assemblies_code_l1_table'),
        ),
        migrations.CreateModel(
            name='Assemblies_Code_L2_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assemblies_Code_L2', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Assemblies_Code_L1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.assemblies_code_l1_table')),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
            options={
                'verbose_name': 'Assemblies Code Level 2',
                'verbose_name_plural': 'Assemblies Codes Level 2',
            },
        ),
        migrations.AddField(
            model_name='estimation_assemblies_table',
            name='Assemblies_Code_L2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.assemblies_code_l2_table'),
        ),
        migrations.CreateModel(
            name='Assemblies_Code_L3_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assemblies_Code_L3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Assemblies_Code_L1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.assemblies_code_l1_table')),
                ('Assemblies_Code_L2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.assemblies_code_l2_table')),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
            ],
            options={
                'verbose_name': 'Assemblies Code Level 3',
                'verbose_name_plural': 'Assemblies Codes Level 3',
            },
        ),
        migrations.AddField(
            model_name='estimation_assemblies_table',
            name='Assemblies_Code_L3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.assemblies_code_l3_table'),
        ),
    ]
