# Generated by Django 5.1.2 on 2024-11-08 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0002_estimation_assemblies_table_company_details_and_more'),
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Equipment_Cost',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Labor_Cost',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Material_Cost',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='OTHERS_Cost',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Resource_Name',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Resource_Type',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Subcontractors_Cost',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Unit_Cost',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Unit_of_Measure',
        ),
        migrations.AlterField(
            model_name='estimation_assemblies_table',
            name='Assembly_Code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Estimation_Assemblies_Resource_Details_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_Cost', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_of_Measure', models.CharField(blank=True, max_length=255, null=True)),
                ('Company_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable')),
                ('Estimation_Assemblies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.estimation_assemblies_table')),
                ('Resource_record', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companyresourcestable')),
            ],
        ),
    ]
