# Generated by Django 5.1.2 on 2024-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0003_remove_estimation_assemblies_table_equipment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation_assemblies_resource_details_table',
            name='Quantity',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimation_assemblies_resource_details_table',
            name='Resource_Budget_Unit_Cost',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
