# Generated by Django 5.1.2 on 2024-11-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0004_estimation_assemblies_resource_details_table_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimation_assemblies_table',
            old_name='Quantity',
            new_name='Unit_of_Measure',
        ),
        migrations.RemoveField(
            model_name='estimation_assemblies_table',
            name='Total_Cost',
        ),
    ]
