# Generated by Django 5.1.2 on 2024-12-24 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0005_rename_quantity_estimation_assemblies_table_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation_assemblies_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimation_assemblies_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
