# Generated by Django 5.1.2 on 2024-12-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0006_estimation_assemblies_table_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation_assemblies_resource_details_table',
            name='Estimation_Assemblies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_assemblies_resourcedetailstable', to='assembliesApp.estimation_assemblies_table'),
        ),
    ]
