# Generated by Django 5.1.2 on 2024-12-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetable',
            name='stock_trasaction_status',
            field=models.CharField(choices=[('', ''), ('Stock-In', 'Stock-In'), ('Stock-Out', 'Stock-Out')], default='', max_length=255),
        ),
    ]
