# Generated by Django 5.1.2 on 2024-12-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('storeApp', '0002_storetable_stock_trasaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetable',
            name='Company_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable'),
        ),
    ]
