# Generated by Django 5.1.2 on 2024-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('manager', 'manager'), ('Viewer', 'Viewer')], default='Admin', max_length=255),
        ),
    ]
