# Generated by Django 5.1.2 on 2024-12-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_user_created_at'),
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_details',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable'),
        ),
    ]
