# Generated by Django 5.1.2 on 2024-12-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembliesApp', '0005_rename_quantity_estimation_assemblies_table_unit_of_measure_and_more'),
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('contractApp', '0005_maincontractdetail_assembly_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comb_assem_code', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.estimation_assemblies_table')),
                ('contract_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractApp.maincontract')),
                ('resource_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyApp.companyresourcestable')),
            ],
        ),
    ]
