# Generated by Django 5.1.2 on 2024-12-27 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('expenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetable',
            name='Company_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable'),
        ),
    ]
