# Generated by Django 5.1.2 on 2024-12-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comb_assem_code', models.CharField(max_length=50, unique=True, verbose_name='Combination Assembly Code')),
                ('assembly_name', models.CharField(max_length=100, verbose_name='Assembly Name')),
            ],
        ),
        migrations.CreateModel(
            name='MainContractDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('item_description', models.TextField(verbose_name='Item Description')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost')),
                ('budget_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget Quantity')),
                ('budget_costs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget Costs')),
                ('markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Markup (%)')),
                ('markup_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Markup Amount')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('target_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target Profit')),
                ('main_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='contractApp.maincontract')),
            ],
        ),
    ]
