# Generated by Django 5.1.2 on 2024-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0002_maincontract_company_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontract',
            name='assembly_name',
        ),
        migrations.RemoveField(
            model_name='maincontract',
            name='comb_assem_code',
        ),
        migrations.AddField(
            model_name='maincontract',
            name='contract_name',
            field=models.CharField(default='', max_length=255, verbose_name='Contract Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincontractdetail',
            name='assembly_name',
            field=models.CharField(default='', max_length=100, verbose_name='Assembly Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincontractdetail',
            name='comb_assem_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Combination Assembly Code'),
            preserve_default=False,
        ),
    ]
