# Generated by Django 5.1.2 on 2024-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0003_remove_maincontract_assembly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontractdetail',
            name='comb_assem_code',
            field=models.CharField(max_length=50, verbose_name='Combination Assembly Code'),
        ),
    ]
