# Generated by Django 5.1.2 on 2024-12-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0005_rename_quantity_estimation_assemblies_table_unit_of_measure_and_more'),
        ('contractApp', '0004_alter_maincontractdetail_comb_assem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontractdetail',
            name='assembly_row',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.estimation_assemblies_table'),
        ),
    ]
