# Generated by Django 5.1.2 on 2024-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0005_maincontractdetail_assembly_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontract',
            name='contract_total_budget_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Budget Cost'),
        ),
        migrations.AddField(
            model_name='maincontract',
            name='contract_total_markup_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Budget Cost'),
        ),
        migrations.AddField(
            model_name='maincontract',
            name='contract_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Budget Cost'),
        ),
        migrations.AddField(
            model_name='maincontract',
            name='contract_total_target_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Budget Cost'),
        ),
    ]
