# Generated by Django 5.1.2 on 2024-12-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembliesApp', '0005_rename_quantity_estimation_assemblies_table_unit_of_measure_and_more'),
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('contractApp', '0006_maincontract_contract_total_budget_costs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContractTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontract_name', models.CharField(max_length=255, verbose_name='Contract Name')),
                ('contract_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Budget Cost')),
                ('company_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable', verbose_name='Company Details')),
            ],
        ),
        migrations.CreateModel(
            name='SubContractDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comb_assem_code', models.CharField(max_length=50, verbose_name='Combination Assembly Code')),
                ('item_description', models.TextField(verbose_name='Item Description')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost')),
                ('subcontract_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget Quantity')),
                ('subcontract_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('assembly_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembliesApp.estimation_assemblies_table')),
                ('contract_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractApp.maincontract')),
                ('sub_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='contractApp.subcontracttable')),
            ],
        ),
    ]
