# Generated by Django 5.1.2 on 2024-12-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0009_remove_subcontracttable_contract_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractdetail',
            name='contract_value',
        ),
        migrations.AddField(
            model_name='subcontracttable',
            name='contract_value',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contractApp.maincontract'),
        ),
    ]
