# Generated by Django 5.1.2 on 2024-12-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0011_maincontract_created_at_maincontract_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontractdetail',
            name='contract_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Budget Quantity'),
        ),
    ]
