# Generated by Django 5.1.2 on 2024-12-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('contractApp', '0012_maincontractdetail_contract_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontractdetail',
            name='contract_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Contract Quantity'),
        ),
        migrations.CreateModel(
            name='MainContractBudgetCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_unit_rates', models.CharField(max_length=255)),
                ('budget_cost', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Resource_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyApp.companyresourcestable')),
                ('contract_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractApp.maincontractdetail')),
            ],
        ),
    ]
