# Generated by Django 5.1.2 on 2024-12-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('contractApp', '0013_alter_maincontractdetail_contract_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainContractBudgetCost',
            new_name='MainContractBudgetCostTable',
        ),
    ]
