# Generated by Django 5.1.2 on 2024-12-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0009_alter_resource_code_l1_table_options_and_more'),
        ('contractApp', '0014_rename_maincontractbudgetcost_maincontractbudgetcosttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontractbudgetcosttable',
            name='company_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailstable', verbose_name='Company Details'),
        ),
    ]
