# Generated by Django 5.1.2 on 2024-12-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0015_maincontractbudgetcosttable_company_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainContractInvoiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Quantity')),
                ('Invoice_Revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Revenue')),
                ('main_contract_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_details_invoice', to='contractApp.maincontractdetail')),
            ],
        ),
    ]
