# Generated by Django 5.1.2 on 2024-12-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0017_maincontractinvoicetable_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontractinvoicetable',
            name='Invoice_Quantity',
        ),
        migrations.RemoveField(
            model_name='maincontractinvoicetable',
            name='Invoice_Revenue',
        ),
        migrations.CreateModel(
            name='MainContractInvoiceDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Quantity')),
                ('Invoice_Revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Revenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_contract_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_details_invoice_details', to='contractApp.maincontractinvoicetable')),
            ],
        ),
    ]
