# Generated by Django 5.1.2 on 2024-12-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0018_remove_maincontractinvoicetable_invoice_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontractinvoicetable',
            name='main_contract_assembly',
        ),
        migrations.AddField(
            model_name='maincontractinvoicedetailstable',
            name='main_contract_assembly',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contract_details_invoice', to='contractApp.maincontractdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincontractinvoicetable',
            name='invoice_contract_row',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contract_invoices', to='contractApp.maincontract'),
            preserve_default=False,
        ),
    ]
