# Generated by Django 5.1.2 on 2024-12-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0019_remove_maincontractinvoicetable_main_contract_assembly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContractInvoiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_contract_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_invoices', to='contractApp.subcontracttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubContractInvoiceDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Quantity')),
                ('Invoice_Revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Revenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_contract_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_details_invoice', to='contractApp.subcontractdetail')),
                ('sub_contract_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_details_invoice_details', to='contractApp.subcontractinvoicetable')),
            ],
        ),
    ]
