# Generated by Django 5.1.2 on 2024-12-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0020_subcontractinvoicetable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractdetail',
            name='subcontract_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SubContract Contract Quantity'),
        ),
        migrations.AlterField(
            model_name='subcontractdetail',
            name='subcontract_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subcontract Total Price'),
        ),
    ]
